AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template used to create ECS Fargte Cluster.'
Parameters:
  ECSClusterName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9\-]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters, or hyphens.
    Default: 'test-cluster'
    Description: The ECS cluster name
    MaxLength: '64'
    MinLength: '1'
    Type: String
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub ${ECSClusterName}
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
